name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: your-image-name:latest

      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: your-ec2-instance-ip
          username: your-ec2-instance-username
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Docker Compose
        run: |
          ssh your-ec2-instance-username@your-ec2-instance-ip "cd /path/to/your/project && docker-compose pull && docker-compose up -d"
